version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  sportsdata.provider:
    image: ${DOCKER_REGISTRY-}sportsdataprovider
    build:
      context: .
      dockerfile: src/SportsData.Provider/Dockerfile
    depends_on:
      - db
